- manifest/net.deltawolf/SettingsRedux/info.json
- manifest/net.deltawolf/ShowSourceLocation/info.json
> Add SettingsRedux and ShowSourceLocation

- manifest/net.raidriar796/NoSteamScreenshots/info.json
- manifest/net.raidriar796/ResoniteIkCulling/info.json
- manifest/net.raidriar796/author.json
Added 
- ResoniteIkCulling
- NoSteamScreenshots
> Added new author and two mods

- manifest/ch.isota/DynBoneWrangler/info.json
- manifest/ch.isota/ResonitePlatformSpoof/info.json
- manifest/ch.isota/author.json
> feat: add author isotach + add 2 mods

- manifest/ninja.badhalo/ResoniteModSettings/info.json
- manifest/ninja.badhalo/author.json
> Add ResoniteModSettings and badhaloninja author info

- manifest/me.art0007i/CapturePrivateUI/info.json
- manifest/me.art0007i/ColorDrop/info.json
- manifest/me.art0007i/ConsistentDashboard/info.json
- manifest/me.art0007i/CreateWorldConfig/info.json
- manifest/me.art0007i/CustomInspectors/info.json
- manifest/me.art0007i/CustomJoinVerifierFix/info.json
- manifest/me.art0007i/CustomUILib/info.json
- manifest/me.art0007i/DefaultToolOverride/info.json
- manifest/me.art0007i/DisableLegacyInventory/info.json
- manifest/me.art0007i/ExtrasButtonTweaks/info.json
- manifest/me.art0007i/FixGrabWorld/info.json
- manifest/me.art0007i/ImportCompactor/info.json
- manifest/me.art0007i/InspectorScroll/info.json
- manifest/me.art0007i/LocalStorage/info.json
- manifest/me.art0007i/NoHeadMenuDash/info.json
- manifest/me.art0007i/ParentalIssues/info.json
- manifest/me.art0007i/PresenceToggle/info.json
- manifest/me.art0007i/QuickFolderOpener/info.json
- manifest/me.art0007i/RemoveComponentAttacherRestriction/info.json
- manifest/me.art0007i/ShadowDistanceChanger/info.json
- manifest/me.art0007i/ShowComponentSlot/info.json
- manifest/me.art0007i/ShowDelegates/info.json
- manifest/me.art0007i/ShowDriveSource/info.json
- manifest/me.art0007i/SpecialItemsLib/info.json
- manifest/me.art0007i/ToolshelfAnarchy/info.json
- manifest/me.art0007i/TrackerModelSwapper/info.json
- manifest/me.art0007i/TransparentCameraEnabler/info.json
- manifest/me.art0007i/ValueProxyExtensions/info.json
- manifest/me.art0007i/author.json
- manifest/me.art0007i/🍀/info.json
some of the categories are wrong, I'll fix it soon™
> me and my mods

- manifest/org.zeith/VDFaceTracking/info.json
- manifest/org.zeith/author.json
> Added VDFaceTracking to the manifest.

- manifest/Banane9/BoundedUIX/info.json
- manifest/Banane9/StopDisappearingLocomotionMenu/info.json
- manifest/Banane9/author.json
Submitting Banane9's Resonite mods with their blessing.
> Add Banane9 and their mods

- manifest/net.dfgHiatus/GTAImporter/info.json
- manifest/net.dfgHiatus/SpeedyURLs/info.json
- manifest/net.dfgHiatus/TarGZImporter/info.json
- manifest/net.dfgHiatus/author.json
Adding an author for @dfgHiatus and a few of their mods that are 100% (I think!) ready for the manifest.
> Add dfgHiatus and some of their mods

- manifest/owo.Nytra/FixSessionBrowser/info.json
Mod is no longer useful as of Beta 2024.1.30.731
> Deprecate FixSessionBrowser

- manifest/dev.hazre/ResonitePrivacyShield/info.json
- manifest/dev.hazre/VRCFTReceiver/info.json
- manifest/dev.hazre/author.json
- Adds new author
- Adds VRCFTReceiver and ResonitePrivacyShield  Mod
> Add author hazre + add 2 mods

- manifest/org.zeith/VDFaceTracking/info.json
> VDFaceTracking 1.0.3

- manifest/ninja.badhalo/FixAltEnter/info.json
- manifest/ninja.badhalo/ResoniteModSettings/info.json
> Added FixAltEnter

- manifest/net.rampa3/Resonite3DDashOnScreen/info.json
- manifest/net.rampa3/author.json
Created my own creator folder and added first Resonite version of 3DDashOnScreen. Numbering of versions continues, like how others did it when transitioning their mods to Resonite.
> Added creator folder and 3DDashOnScreenResonite

- manifest/net.raidriar796/ResoniteIkCulling/info.json
- manifest/net.raidriar796/StresslessHeadless/info.json
- manifest/net.raidriar796/yt-dlp-Updater/info.json
Includes updated versions for ResoniteIkCulling and StresslessHeadless
> Update 2 mods

- manifest/ninja.badhalo/DeselectOwnGizmos/info.json
> Added DeselectOwnGizmos

- manifest/net.dfgHiatus/CacheGetClapped/info.json
- manifest/net.dfgHiatus/FuckMirrors/info.json
- manifest/net.dfgHiatus/MTLImporter/info.json
- manifest/net.dfgHiatus/PimaxEyeTracking/info.json
- manifest/net.dfgHiatus/SVGImporter/info.json
- manifest/net.dfgHiatus/VRMLImporter/info.json
- manifest/net.dfgHiatus/ZipImporter/info.json
Adds 7 new mods from @dfgHiatus.
> Add 7 more dfgHiatus mods

- manifest/ninja.badhalo/EnumDropdown/info.json
- manifest/ninja.badhalo/Optizoom/info.json
> Add Optizoom and EnumDropdown to the manifest

- manifest/owo.Nytra/HeadlessToolPermissionKickCrashFix/info.json
> Deprecate HeadlessToolPermissionKickCrashFix

- manifest/owo.Nytra/InspectorDelegateCaller/info.json
My fork of the mod which was originally made by eia485 and seems to be no longer maintained by them.
> Add InspectorDelegateCaller v1.4.1

- manifest/com.Sinduy/QuestPro4Resonite/info.json
- manifest/com.Sinduy/author.json
- manifest/com.Sinduy/libalxr-sharp/info.json
> Add author Sinduy and QuestPro4Resonite mod

- manifest/me.art0007i/ColorDrop/info.json
- manifest/me.art0007i/MyInspectors/info.json
- manifest/me.art0007i/ShowDelegates/info.json
the changelogs texts changed cause I actually added those mods to the manifest myself without realizing that it's already been done by someone else for me
for the future please do not update my own mods for me, I can do it myself easily. if you need it updated quick then msg me on discord preferably. it just causes merge conflicts and is annoying
> some updates

- manifest/net.raidriar796/NoSteamScreenshots/info.json
- manifest/net.raidriar796/ResoniteIkCulling/info.json
- manifest/net.raidriar796/StresslessHeadless/info.json
- manifest/net.raidriar796/yt-dlp-Updater/info.json
Updated:
- ResoniteIkCulling
- yt-dlp updater
Platform info added to:
- NoSteamScreenshots
> Updated 2 mods, added platform info for 1 mod

- manifest/ninja.badhalo/EnumDropdown/info.json
> EnumDropdown v2.1.1 Update

- manifest/dev.baru/ResoniteScreenshotExtensions/info.json
ResoniteScreenshotExtensions v1.1.1 Update
> ResoniteScreenshotExtensions v1.1.1 Update

- manifest/dev.baru/BetterInventoryBrowser/info.json
BetterInventoryBrowser v0.6.2 Update
> BetterInventoryBrowser v0.6.2 Update

- manifest/net.Cyro/CherryPick/info.json
- manifest/net.Cyro/author.json
> Add CherryPick

- manifest/ninja.badhalo/Optizoom/info.json
> Optizoom v2.1.2 Update

- manifest/dev.baru/ResoniteScreenshotExtensions/info.json
ResoniteScreenshotExtensions v1.1.2 Update
> ResoniteScreenshotExtensions v1.1.2 Update

- manifest/org.zeith/VDFaceTracking/info.json
> VDFaceTracking 1.1.0

- manifest/dev.hazre/ResonitePrivacyShield/info.json
> Add ResonitePrivacyShield v2.0.3

- manifest/net.hantabaru1014/SaveItemTweaks/info.json
> SaveItemTweaks v2.0.2 Update

- manifest/dev.baru/BetterInventoryBrowser/info.json
BetterInventoryBrowser v0.6.3 Update
> BetterInventoryBrowser v0.6.3 Update

- manifest/dev.baru/ResoniteScreenshotExtensions/info.json
ResoniteScreenshotExtensions v1.1.3 Update
> ResoniteScreenshotExtensions v1.1.3 Update

- manifest/net.catshark/ReArmature/info.json
ReArmature v2.1.2 Update
A rogue missing brackets kept breaking the info. Finally got it figured out.
> ReArmature v2.1.2 Update

- manifest/net.raidriar796/NoSteamScreenshots/info.json
The feature is now native to the platform
> NoSteamScreenshots mod deprecation

- manifest/je.dj/CopyHyperlink/info.json
- manifest/je.dj/GradientDriverEasing/info.json
- manifest/je.dj/author.json
> Add CopyHyperlink and GradientDriverEasing

- manifest/net.Cyro/CherryPick/info.json
> Updated CherryPick to v1.1.0

- manifest/net.Cyro/EffortlessEfficiency/info.json
> Added EffortlessEfficiency

- manifest/me.art0007i/ShowDelegates/info.json
- manifest/me.art0007i/ValueProxyExtensions/info.json
hopefully i didnt mess up sha hash but we'll see
> update for type system

- manifest/je.dj/CopyHyperlink/info.json
- manifest/je.dj/GradientDriverEasing/info.json
> Add new releases for CopyHyperlinks & GradientDriverEasing.

- manifest/dev.baru/ResoniteScreenshotExtensions/info.json
ResoniteScreenshotExtensions v1.1.4 Update
> ResoniteScreenshotExtensions v1.1.4 Update

- manifest/com.Kannya/ColourMyFiles/info.json
- manifest/com.Kannya/Console/info.json
(it matches the class name FilesColours, still a unique harmony id. - Name override does not match harmony suffix however, as I didn't think it matters.)
> Update Console to 1.0.1: MonkeyLoader Support, Add ColourMyFiles

- manifest/me.art0007i/CustomInspectors/info.json
- manifest/me.art0007i/ShowComponentSlot/info.json
since it's in the game now
also i accidentally 2 commits
> deprecate ShowComponentSlot

- manifest/org.zeith/VDFaceTracking/info.json
> VDFaceTracking 1.1.1

- manifest/me.art0007i/DisableLegacyInventory/info.json
I always forget to mark them as such
> deprecated this

- manifest/semmiedev/NoDoubleTapSprint/info.json
- manifest/semmiedev/author.json
> Add NoDoubleTapSprint mod entry

- manifest/lc.j4/HeadlessPrometheusExporter/info.json
- manifest/lc.j4/author.json
> Add my mods and myself

- manifest/me.art0007i/DisableLegacyInventory/info.json
- manifest/me.art0007i/OutOfSightOverride/info.json
ye i keep messing up my branch to where it has commits from the last pull, but it shouldnt matter especially cause I think stuff is squashed when it's merged into this repo
> add OutOfSightOverride

- manifest/me.art0007i/FixMigratedItemMessages/info.json
FixMigratedItemMessages
should mod descriptions contain md stuff? either way md is human readable enough to where its fine
> add FixMigratedItemMessages

- manifest/net.NepuShiro/ChangeJoinLeaveSound/info.json
- manifest/net.NepuShiro/FluxFinder/info.json
- manifest/net.NepuShiro/ResoTabbed/info.json
- manifest/net.NepuShiro/ResoniteFixContactIcons/info.json
- manifest/net.NepuShiro/ResoniteSlotInspectorCounter/info.json
- manifest/net.NepuShiro/author.json
> Add NepuShiro's mods

- manifest/com.frozenreflex/Thundagun/info.json
Update to 1.2.0: https://github.com/Frozenreflex/Thundagun/releases/tag/1.2.0
> Update Thundagun 1.2.0

- manifest/RyanVittore/ArrayEditing/info.json
- manifest/RyanVittore/author.json
> Add ArrayEditing 1.0.0

- manifest/net.NepuShiro/ResoniteSlotInspectorCounter/info.json
> Update ResoniteSlotInspectorCounter 1.5.0

- manifest/me.art0007i/ValueProxyExtensions/info.json
> Update ValueProxyExtensions 2.1.2

- manifest/me.art0007i/ResoniteImGuiLib/info.json
> Update ResoniteImGuiLib 1.1.0

- manifest/dev.baru/ResoniteScreenshotExtensions/info.json
> Update ResoniteScreenshotExtensions 1.2.0

- manifest/me.art0007i/IKnowWhatImDoing/info.json
I speedrun making mods now I guess 💨💨💨🚀
> Add IKnowWhatImDoing 1.0.0

- manifest/ErrorJan/EnableToolspawnInVR/info.json
- manifest/ErrorJan/FixMirrorSteamVRIPDOffset/info.json
- manifest/ErrorJan/IgnoreControllerAxis/info.json
- manifest/ErrorJan/author.json
Added EnableToolspawnInVR
Added FixMirrorSteamVRIPDOffset
Added IgnoreControllerAxis
> Add ErrorJan's 3 Mods

- manifest/me.art0007i/ValueProxyExtensions/info.json
it fixes it for latest version
> Update ValueProxyExtensions 2.1.3

- manifest/RyanVittore/ArrayEditing/info.json
- manifest/RyanVittore/author.json
> Update ArrayEditing 1.0.1

- manifest/me.art0007i/DuplicateFix/info.json
> Update DuplicateFix 1.0.2

- manifest/me.art0007i/DuplicateFix/info.json
> duplicate fix fix

- manifest/news.fawx/LocalAllowList/info.json
- manifest/news.fawx/author.json
> Add LocalAllowList

- manifest/ninja.badhalo/OrbCartridgeAutoScoop/info.json
- manifest/ninja.badhalo/author.json
> Add OrbCartridgeAutoScoop v2.0.1

- manifest/ninja.badhalo/ShowObjectRootSlotNameInSubtitleOnInspectorsForSelectedSlotMod/info.json
> Add SORSNISOIFSSM v1.0.0

- manifest/ninja.badhalo/FriendlyInventoryAvatars/info.json
> Add FriendlyInventoryAvatars v1.0.0

- manifest/net.deltawolf/Fish/info.json
> Add Fish 1.0.0

- manifest/je.dj/BoundedUIX/info.json
> RML fork of BoundedUIX

- manifest/me.art0007i/CustomInspectors/info.json
- manifest/me.art0007i/DuplicateFix/info.json
apparently I forgor to make a PR for duplicate fix despite having a commit on my fork of the manifest already... oops
> mod updats.

- manifest/me.art0007i/ShowDelegates/info.json
> new version of ShowDelegates

- manifest/com.__Choco__/HandAligner/info.json
> add HandAligner

- manifest/ninja.badhalo/AvatarCreatorUtils/info.json
> Add AvatarCreatorUtils v2.0.0

- manifest/com.__Choco__/HostCrashGuard/info.json
There have been some small improvements, you can see all of the changes [here](https://github.com/AwesomeTornado/Resonite-HostCrashGuard/releases)
> HostCrashGuard V2.2.0

- manifest/net.kazu0617/SessionTweaks/info.json
- manifest/net.kazu0617/author.json
> Add SessionTweaks

- manifest/dev.baru/ResoniteScreenshotExtensions/info.json
Added missing prior versions and hashes + new 2.0.1 version
> ResoniteScreenshotExtensions Update v2.0.1

- manifest/com.Kannya/ColourMyFiles/info.json
- manifest/com.Kannya/Console/info.json
- manifest/com.Kannya/author.json
> Update ColourMyFiles to 1.0.1, adjust my jsons to spaces instead of tabs to match json standard

- manifest/net.dfgHiatus/ZipImporter/info.json
> Update ZipImporter 2.1.2

- manifest/dev.baru/ResoniteScreenshotExtensions/info.json
Add [ResoniteScreenshotExtensions 2.0.2](https://github.com/hantabaru1014/ResoniteScreenshotExtensions/releases/tag/v2.0.2) made by [hantabaru1014](https://github.com/hantabaru1014)
> Update ResoniteScreenshotExtensions 2.0.2

- manifest/net.deltawolf/DisableSRAnipal/info.json
> Update DisableSRAnipal 1.0.1

- manifest/com.Sinduy/SlotInspectorHighlighter/info.json
Update SlotInspectorHighlighter to version 1.0.1
> Update SlotInspectorHighlighter v1.0.1

- manifest/Restrainite/Restrainite/info.json
- manifest/Restrainite/author.json
> Add Restrainite Mod

- manifest/Restrainite/Restrainite/info.json
> Update Restrainite to 1.2.9

- manifest/com.__Choco__/ResoniteMP3/info.json
This is the .NET9 update to ResoniteMP3
- moves from NAudio to FFMPEG.
- uses OGG instead of WAV when importing files.
> ResoniteMP3 .NET9

- manifest.json
- manifest/org.zeith/VDFaceTracking/info.json
> Update VDFaceTracking 1.1.2

- manifest/owo.Nytra/ColorMyProtoFlux/info.json
- manifest/owo.Nytra/LogFlush/info.json
- manifest/owo.Nytra/NoTankControls-InspectorScrollCompatible/info.json
- manifest/owo.Nytra/ScrollableFieldEditors/info.json
Update ColorMyProtoFlux, LogFlush, NoTankControls-InspectorScrollCompatible and ScrollableFieldEditors
> Update ColorMyProtoFlux, LogFlush, NoTankControls-InspectorScrollCompatible and ScrollableFieldEditors

- manifest/je.dj/BoundedUIX/info.json
- manifest/je.dj/CopyHyperlink/info.json
- manifest/je.dj/GradientDriverEasing/info.json
- manifest/je.dj/SwapToDynamicBlendShapeDriver/info.json
> djsime1's mod updates + SwapToDynamicBlendShapeDriver

- manifest/ErrorJan/EnableToolspawnInVR/info.json
> Update EnableToolSpawnInVR 1.0.1

- manifest/ErrorJan/IgnoreControllerAxis/info.json
> Update IgnoreControllerAxis 1.1.0

- manifest/dev.baru/ResoniteScreenshotExtensions/info.json
> Update ResoniteScreenshotExtensions 2.1.0

- manifest/com.nekometer.esnya/ResoniteMetricsCounter/info.json
- [not my mod] Follow the [Resonite Policies and Guidelines](https://resonite.com/policies/) and [Mod Submission Guidelines](https://github.com/resonite-modding-group/resonite-mod-manifest/wiki/Submission-Guidelines)
> Update ResoniteMetricsCounter to 8.0.0

- manifest/com.__Choco__/HandAligner/info.json
.NET9 recompile, with new experimental support for automatic scaling, and a setting to automatically turn off symmetry by default for more accurate positioning.
> Update HandAligner 2.0.1

- manifest/me.art0007i/MyInspectors/info.json
> Update MyInspectors 2.0.4

- manifest/lc.j4/HeadlessPrometheusExporter/info.json
> Update HeadlessPrometheusExporter 1.2.4

- manifest/net.headassbtw/OpenXREyeTracking/info.json
> Update OpenXREyeTracking 1.0.3

- manifest/com.Sinduy/SlotInspectorHighlighter/info.json
> Update SlotInspectorHighlighter 1.0.2

- manifest/com.scicortex/CyberFingerMod/info.json
- manifest/com.scicortex/author.json
> Add CyberFingerMod 1.0.0

- manifest/net.deltawolf/PermissionControl/info.json
> Update PermissionControl 2.0.1

- manifest/me.art0007i/MyInspectors/info.json
> Update MyInspectors 2.1.0

- manifest/me.art0007i/LogCleaner/info.json
> Update LogCleaner 1.1.2

- manifest/me.art0007i/CustomInspectors/info.json
> Update CustomInspectors 2.2.1

- manifest/com.Dexy/ProtoFluxOverhaul/info.json
- [notmine] Follow the [Resonite Policies and Guidelines](https://resonite.com/policies/) and [Mod Submission Guidelines](https://github.com/resonite-modding-group/resonite-mod-manifest/wiki/Submission-Guidelines)
> Update ProtoFluxOverhaul 1.4.6
