resonite-modding-group/resonite-mod-manifest

manifest/com.example/author.json
I didn't realize that "AuthorName" was something I'm supposed to change, because it sounds like a plausible json key. I think "ExampleAuthor" sounds much more like something you need to replace
=> Update example author to be less misleading

manifest/U-xyla/NoTankControls/info.json, manifest/U-xyla/author.json
Note that the prefix used is U-xyla, my old Neos username, as I didn't change the harmony Mod ID when releasing the Resonite version. I would give it an appropriate 'reverse domain' style prefix, but I don't want to update the mod unnecessarily.
=> Add NoTankControls v1.0.0-resonite

manifest/me.art0007i/ImGuiUnityInject/info.json, manifest/me.art0007i/ResoniteImGuiLib/info.json
so ImGuiUnityInject is probably a pretty weird one to add
The cimgui dlls are sourced from me making a fresh unity project on unity 2019, copying the entire plugins folder from https://github.com/realgamessoftware/dear-imgui-unity/tree/master/Plugins into assets, and building the game. After this I simply took the dlls from the build and those are the ones present here.
also idk if the artifact filenames are supposed to be like they are
=> add im gui stuff

manifest/lc.j4/HeadlessPrometheusExporter/info.json
Adding this new version quickly since `2024.9.30.1215` introduced changes that break older versions of the mod.
=> chore: add new release

manifest/net.Cyro/Outflow/info.json
No longer should be needed as of 2024.9.30.1215
=> Deprecate Outflow

manifest/net.rampa3/Resonite3DDashOnScreen/info.json, manifest/net.rampa3/author.json
This PR adds all currently avalable versions of 3DDashOnScreenResonite to the manifest. It is combination of never made PR for the initial version of 3DDashOnScreenResonite, and PR for current update, which merges commit https://github.com/rampa3/3DDashOnScreenResonite/commit/a3a95a5799922ba00cc45dc990e31f3b7f35dae4 from [NepuShiro](https://github.com/NepuShiro), fixing the mod after breakage on the latest version of Resonite.
=> Added 3DDashOnScreenResonite to manifest

manifest/lc.j4/HeadlessPrometheusExporter/info.json
Update 1.2.2 building against .NET 9 + security fix in System.Text.Json.
https://g.j4.lc/general-stuff/resonite/headless-prometheus-exporter/-/releases/1.2.2
=> Update HeadlessPrometheusExporter 1.2.2

manifest/owo.Nytra/HotReloadLib/info.json
This release changes the artifact to be a ZIP file containing two DLLs. Let me know if this is a problem.
=> Update HotReloadLib 3.0.0

manifest/com.frozenreflex/Thundagun/info.json
The version of the mod that is on the manifest is crashing. It is also missing a lot of stuff for PhotonDust and SphericalHarmonics which lead to particles not showing and world ambient lighting not working.
I may add this missing stuff later, but for now I think the mod should be hidden so people don't download it and then have a bad experience.
=> Mark Thundagun as deprecated

manifest/com.__Choco__/ResoniteMP3/info.json
Add version 2.1.0 of ResoniteMP3
QOL improvements: Removed random filenames.
This mod update only changes how temp files are stored. Instead of randomizing filenames in order to prevent conflicts, a new randomly named folder is created on every import which contains the properly named file within. All of these folders are still contained inside of the temp folder made for ResoniteMP3, and deleted on app start.
=> Update ResoniteMP3 to V2.1.0

manifest/dev.discordnet/Core/info.json, manifest/dev.discordnet/Rest/info.json, manifest/dev.discordnet/Webhook/info.json, manifest/dev.discordnet/author.json, manifest/page.newweb/HeadlessTweaks/info.json, manifest/page.newweb/author.json
This includes 
- New_Project_Final_Final_WIP's author info 
- DiscordNet's Core, Rest, Webhook, and author info
This requires net9 and there's not a way to specify that currently
Also DiscordNet only shares downloads to NugetPackages, these dlls on the HeadlessTweaks release page are pulled from those
=> HeadlessTweaks v2.1.9

manifest/com.__Choco__/ResoniteAprilFools/info.json
This is a dead simple mod that patches the engine check for April Fools content and always returns true.
=> Add mod: ResoniteAprilFools

manifest/Banane9/BoundedUIX/info.json
Add the deprecated flag because it was last updated in 2023 and won't be maintained because the newer version is for MonkeyLoader.
=> Deprecate Banane9's BoundedUIX

manifest/com.__Choco__/HostCrashGuard/info.json
I accidentally introduced a bug in the previous version that flagged many valid component types as invalid. This release should fix that. More information can be found [here](https://github.com/AwesomeTornado/Resonite-HostCrashGuard/issues/10).
=> Update HostCrashGuard to V2.4.5

manifest/com.__Choco__/CustomShaderLib/info.json, manifest/com.__Choco__/DoublePrecision/info.json
This PR adds in both CustomShaderLib, and DoublePrecision. While I believe that I have filled out the JSON correctly to add each mod, DoublePrecision relies on CustomShaderLib as a dependency and will break materials if used on its own. Is there any officially supported way to list dependencies, or should I just add CustomShaderLib as another artifact?
=> Add CustomShaderLib And DoublePrecision

manifest.json, manifest/org.zeith/VDFaceTracking/info.json
Hotfix another issue caused from .net 9, making Resonite fail to shutdown properly.
=> Update VDFaceTracking 1.1.3

manifest/com.tabbynet/ResonitePSVR2/info.json, manifest/com.tabbynet/author.json
Adding my hardware enablement mod for easier install and more visibility for PS VR2 owners!
=> Add ResonitePSVR2 1.0.1

manifest/Banane9/StopDisappearingLocomotionMenu/info.json
Broken on .NET 9 and won't be fixed.
By the way, sctanf has made a [fork](https://github.com/sctanf/ResoniteStopDisappearingLocomotionMenu) but the functionality of this mod is included in ML's GamePack so I'm not sure if it's worth even adding it to the manifest.
=> Deprecate ResoniteStopDisappearingLocomotionMenu

manifest/co.uk.AlexW-578/CustomProtofluxBrowser/info.json
Adds SpecialItemsLib as a dependency as it is required to work, also adds 2 tags to assist in search
=> Add tags and dependency for CustomProtofluxBrowser

manifest/com.GrandtheUK/MoreReferenceProxies/info.json
I have also added @EIA485 as an additionalAuthor as they are the original author of the HarmonyPatch used in this port.
=> Add MoreReferenceProxies 1.0.1
